# Generated by Django 5.1.3 on 2024-12-04 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.FloatField()),
                ('total_price', models.PositiveIntegerField()),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='instrument.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
